import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import { agentMetaToToml, isRyoKitToml } from '../src/utils/toml-agent.js';

describe('agentMetaToToml', () => {
  test('produces TOML with sentinel comment', () => {
    const result = agentMetaToToml({ name: 'reviewer', description: 'Reviews code.' });
    assert.ok(result.startsWith('# Generated by ryo-kit from .ryo/agents/reviewer.agent.md'));
  });

  test('includes name and description fields', () => {
    const result = agentMetaToToml({ name: 'reviewer', description: 'Reviews code.' });
    assert.ok(result.includes('name = "reviewer"'));
    assert.ok(result.includes('description = "Reviews code."'));
  });

  test('escapes quotes in description', () => {
    const result = agentMetaToToml({ name: 'reviewer', description: 'Says "hello" often.' });
    assert.ok(result.includes('description = "Says \\"hello\\" often."'));
  });

  test('includes developer_instructions with body', () => {
    const result = agentMetaToToml({
      name: 'reviewer',
      description: 'Reviews code.',
      body: 'You are a code reviewer.\nBe thorough.',
    });
    assert.ok(result.includes('developer_instructions = """'));
    assert.ok(result.includes('You are a code reviewer.\nBe thorough.'));
    assert.ok(result.includes('"""'));
  });

  test('uses empty body by default', () => {
    const result = agentMetaToToml({ name: 'reviewer', description: 'Reviews code.' });
    assert.ok(result.includes('developer_instructions = """'));
    // Body is empty, so the line after """ should be empty then """
    assert.ok(result.includes('"""\n\n"""'));
  });
});

describe('isRyoKitToml', () => {
  test('returns true for ryo-kit generated TOML', () => {
    const toml = agentMetaToToml({ name: 'reviewer', description: 'Reviews code.' });
    assert.equal(isRyoKitToml(toml), true);
  });

  test('returns false for non-ryo-kit TOML', () => {
    assert.equal(isRyoKitToml('name = "reviewer"'), false);
  });

  test('returns false for empty string', () => {
    assert.equal(isRyoKitToml(''), false);
  });

  test('returns true for content starting with sentinel', () => {
    assert.equal(isRyoKitToml('# Generated by ryo-kit from something'), true);
  });
});
