const SENTINEL = '# Generated by ryo-kit from';

export function agentMetaToToml(agentMeta) {
  const { name, description, body = '' } = agentMeta;
  const escapedDesc = description.replace(/"/g, '\\"');
  const escapedBody = body.replace(/"""/g, '""\\\"');
  return [
    `${SENTINEL} .ryo/agents/${name}.agent.md`,
    `name = "${name}"`,
    `description = "${escapedDesc}"`,
    '',
    `developer_instructions = """`,
    escapedBody,
    `"""`,
    '',
  ].join('\n');
}

export function isRyoKitToml(content) {
  return content.startsWith(SENTINEL);
}
